// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHwEfbWWBTjY4w01Q1S35-3e54l_5Mowk',
    appId: '1:562001608316:web:ff93c2695c63d5492e13f9',
    messagingSenderId: '562001608316',
    projectId: 'designerx-652b0',
    authDomain: 'designerx-652b0.firebaseapp.com',
    storageBucket: 'designerx-652b0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV5L7aob32HwZ3TleZNnyAz73Af1akijg',
    appId: '1:562001608316:android:c573523909b40a242e13f9',
    messagingSenderId: '562001608316',
    projectId: 'designerx-652b0',
    storageBucket: 'designerx-652b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd2aLhBiUciDzzH6pEW67TTrj_HzgejQI',
    appId: '1:562001608316:ios:b9bdcf543cc4dd502e13f9',
    messagingSenderId: '562001608316',
    projectId: 'designerx-652b0',
    storageBucket: 'designerx-652b0.firebasestorage.app',
    iosBundleId: 'com.example.feArt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd2aLhBiUciDzzH6pEW67TTrj_HzgejQI',
    appId: '1:562001608316:ios:b9bdcf543cc4dd502e13f9',
    messagingSenderId: '562001608316',
    projectId: 'designerx-652b0',
    storageBucket: 'designerx-652b0.firebasestorage.app',
    iosBundleId: 'com.example.feArt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHwEfbWWBTjY4w01Q1S35-3e54l_5Mowk',
    appId: '1:562001608316:web:b8ac47a426b1f8362e13f9',
    messagingSenderId: '562001608316',
    projectId: 'designerx-652b0',
    authDomain: 'designerx-652b0.firebaseapp.com',
    storageBucket: 'designerx-652b0.firebasestorage.app',
  );
}
